### ISSUE TITLE
Relicencier sous une licence de logiciel libre

### ISSUE THREAD

**Issue by AXDOOMER** [ClubCedille/RocketCam#6]
MIT est une licence de logiciel open source. CEDILLE est un club de logiciel libre. Je suggère donc qu'on utilise une licence de logiciel libre comme la GPL2 ou GPL3 afin de respecter la philosophie du club. 

Comme notre code roulera sur un Raspberry Pi Zero et que notre code ne sera pas mixé avec celui de l'autre club, elle conviendra bien au projet, car il ne sera pas limité par ce facteur.

**Comment by AXDOOMER** [comment]
En fait, c'est ton projet alors c'est toi qui décide. C'est peut-être juste moi qui ne serait pas motivé à travailler sur un projet open source contrairement à un projet de logiciel libre. Je ne m'y oppose pas, car c'est mieux que le projet soit sous une licence open source (non-copyleft) qu'aucune licence du tout.

**Comment by JulienRobitaille** [comment]
Je t'invite a lire: https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses#cite_note-ref_FSF-28 et https://www.gnu.org/licenses/license-list.html

La licence du projet est approuvé par le FSF comme une licence 

Ils disent en autre: This is a fine license for a small program.

Je pense bien que pour l'instant ce projet restera un petit projet. 
La bonne nouvelle, c'est que si on change son envergure, nous aurons le champs libre pour la re-licencer avec une licence qui s'appliquera mieux.

**Comment by AXDOOMER** [comment]
Approuvé par la FSF, mais pas copyleft. Mais comme tu dis, c'est correcte pour l'instant. :thumbsup:

**Comment by JulienRobitaille** [comment]
Personnellement, j'aime mieux laisser les gens faire n'importe quoi qu'ils veulent avec ce genre de projet.
Je n'aime pas l'idée de forcer les gens à redistribuer leur travaux sous une licence copyleft. Je préfère leur laisser le choix.
